In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('air_quality_data.csv')
df.head()

,T,TM,Tm,SLP,H,VV,V,VM,AQI
0,34.487226,21.986289,17.350426,971.650071,58.813960,2.336514,9.761894,15.651720,78.478359
1,38.073213,25.094742,14.683795,936.217329,25.654855,7.169882,2.050995,11.586475,178.843648
2,18.612802,15.221732,25.427554,929.583675,64.094329,5.190567,8.110502,18.374179,121.121967
3,38.279223,10.955384,26.469589,928.093295,62.592577,7.297374,7.593597,7.593427,105.331291
4,23.578124,28.111091,12.202318,931.441683,67.938905,5.565152,12.520325,14.566863,79.150596

In [3]:
df.shape

(100, 9)

In [4]:
df.dtypes

T      float64
TM     float64
Tm     float64
SLP    float64
H      float64
VV     float64
V      float64
VM     float64
AQI    float64
dtype: object

In [5]:
df.isnull().sum()

T      0
TM     0
Tm     0
SLP    0
H      0
VV     0
V      0
VM     0
AQI    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.describe()

,T,TM,Tm,SLP,H,VV,V,VM,AQI
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,23.840701,25.671695,26.039155,976.807036,57.768711,4.681835,9.436343,10.663012,122.494738
std,8.517859,8.120175,9.149371,46.881283,22.765745,2.810385,6.116517,5.060727,46.700061
min,10.229853,10.757962,10.319092,900.835055,20.526411,0.078430,0.041893,1.212408,51.212528
25%,16.737637,19.065649,17.915770,935.760751,40.094631,2.349527,3.617397,6.718412,80.638491
50%,22.920637,25.904151,25.823982,970.347202,59.023972,4.485097,9.011938,10.421840,118.401572
75%,31.384160,32.326568,33.781015,1017.527365,77.443141,6.979787,14.860525,14.689407,168.157977
max,39.756301,39.144808,39.932782,1049.758195,99.625871,9.710185,19.785412,19.949397,199.648610